version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-demo
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  adminer:
    container_name: adminer-mysql
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db